// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: google/antigravity/proto/genai_json_annotations.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonType int32

const (
	JsonType_JSON_TYPE_UNSPECIFIED JsonType = 0
	JsonType_JSON_TYPE_OBJECT      JsonType = 1
	JsonType_JSON_TYPE_ARRAY       JsonType = 2
	JsonType_JSON_TYPE_VALUE       JsonType = 3
)

// Enum value maps for JsonType.
var (
	JsonType_name = map[int32]string{
		0: "JSON_TYPE_UNSPECIFIED",
		1: "JSON_TYPE_OBJECT",
		2: "JSON_TYPE_ARRAY",
		3: "JSON_TYPE_VALUE",
	}
	JsonType_value = map[string]int32{
		"JSON_TYPE_UNSPECIFIED": 0,
		"JSON_TYPE_OBJECT":      1,
		"JSON_TYPE_ARRAY":       2,
		"JSON_TYPE_VALUE":       3,
	}
)

func (x JsonType) Enum() *JsonType {
	p := new(JsonType)
	*p = x
	return p
}

func (x JsonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JsonType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_antigravity_proto_genai_json_annotations_proto_enumTypes[0].Descriptor()
}

func (JsonType) Type() protoreflect.EnumType {
	return &file_google_antigravity_proto_genai_json_annotations_proto_enumTypes[0]
}

func (x JsonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A fixed key-value pair that exists in the JSON representation but does not
// correspond to any proto field. During deserialization, the parser strips this
// key from the JSON input. This is useful for messages like Interaction that
// have a `reserved object;` field and expect `{"object": "interaction"}` in
// the JSON payload.
type StaticJsonField struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StaticJsonField) Reset() {
	*x = StaticJsonField{}
	mi := &file_google_antigravity_proto_genai_json_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticJsonField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticJsonField) ProtoMessage() {}

func (x *StaticJsonField) ProtoReflect() protoreflect.Message {
	mi := &file_google_antigravity_proto_genai_json_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StaticJsonField) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *StaticJsonField) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *StaticJsonField) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StaticJsonField) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StaticJsonField) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StaticJsonField) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StaticJsonField) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *StaticJsonField) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

type StaticJsonField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *string
	Value *string
}

func (b0 StaticJsonField_builder) Build() *StaticJsonField {
	m0 := &StaticJsonField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

var file_google_antigravity_proto_genai_json_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000029,
		Name:          "gaos.parsing.is_union",
		Tag:           "varint,525000029,opt,name=is_union",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000030,
		Name:          "gaos.parsing.subtype_source",
		Tag:           "varint,525000030,opt,name=subtype_source",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000031,
		Name:          "gaos.parsing.is_required",
		Tag:           "varint,525000031,opt,name=is_required",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000032,
		Name:          "gaos.parsing.union_name",
		Tag:           "bytes,525000032,opt,name=union_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000215,
		Name:          "gaos.parsing.json_discriminator",
		Tag:           "bytes,525000215,opt,name=json_discriminator",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000216,
		Name:          "gaos.parsing.json_discriminator_value",
		Tag:           "bytes,525000216,opt,name=json_discriminator_value",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000217,
		Name:          "gaos.parsing.subtype_source_field",
		Tag:           "varint,525000217,opt,name=subtype_source_field",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000218,
		Name:          "gaos.parsing.json_only_discriminator",
		Tag:           "bytes,525000218,opt,name=json_only_discriminator",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000219,
		Name:          "gaos.parsing.additional_properties",
		Tag:           "varint,525000219,opt,name=additional_properties",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         525000220,
		Name:          "gaos.parsing.json_discriminator_values",
		Tag:           "bytes,525000220,rep,name=json_discriminator_values",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         525000221,
		Name:          "gaos.parsing.add_union_value",
		Tag:           "bytes,525000221,rep,name=add_union_value",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000222,
		Name:          "gaos.parsing.flexible_map",
		Tag:           "varint,525000222,opt,name=flexible_map",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000227,
		Name:          "gaos.parsing.sub_content_name",
		Tag:           "bytes,525000227,opt,name=sub_content_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         535802949,
		Name:          "gaos.parsing.enum_value_name",
		Tag:           "bytes,535802949,opt,name=enum_value_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StaticJsonField)(nil),
		Field:         535801962,
		Name:          "gaos.parsing.add_static_field",
		Tag:           "bytes,535801962,opt,name=add_static_field",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*JsonType)(nil),
		Field:         535801963,
		Name:          "gaos.parsing.message_json_type",
		Tag:           "varint,535801963,opt,name=message_json_type,enum=gaos.parsing.JsonType",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
}

// Extension fields to descriptorpb.OneofOptions.
var (
	// Marks a `oneof` as a union. Instead of wrapping the active field in an
	// object keyed by the field name, the content of the active field is
	// flattened directly into the parent JSON object.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message MyUnion {
	//	  oneof content {
	//	    option (gaos.parsing.is_union) = true;
	//	    string text = 1;
	//	    int32 number = 2;
	//	  }
	//	}
	//
	// Proto `text: "hello"` -> JSON: `"hello"` (if used as a primitive union)
	// or flattened into the parent object.
	//
	// optional bool is_union = 525000029;
	E_IsUnion = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[0]
	// Marks a `oneof` as containing subtype messages for polymorphic resolution.
	// Supports both Explicit mode (using `json_discriminator` on fields) and
	// Implicit mode (using the `oneof` name as the JSON key).
	//
	// See (internal link) for details and examples.
	//
	// optional bool subtype_source = 525000030;
	E_SubtypeSource = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[1]
	// Indicates that the `oneof` must have one of its fields set.
	// This is used by the OAD generator to mark the field as required
	// in the OpenAPI specification.
	//
	// See (internal link) for details and examples.
	//
	// optional bool is_required = 525000031;
	E_IsRequired = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[2]
	// The name of the union to be used in the generated OpenAPI schema.
	// If not set, defaults to the oneof name.
	//
	// See (internal link) for details and examples.
	//
	// optional string union_name = 525000032;
	E_UnionName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Used in explicit union mode. Specifies the JSON key that acts as the
	// discriminator to determine which field of a `oneof` should be populated.
	// If not set, implicit mode is used (using the `oneof` name as key).
	//
	// See (internal link) for details and examples.
	//
	// optional string json_discriminator = 525000215;
	E_JsonDiscriminator = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[4]
	// Specifies the value that the discriminator key must have in the JSON
	// payload to map to this specific field.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message ObjectUnion {
	//	  oneof content {
	//	    option (gaos.parsing.is_union) = true;
	//	    MessageA a = 1 [
	//	      (gaos.parsing.json_discriminator) = "type",
	//	      (gaos.parsing.json_discriminator_value) = "A"
	//	    ];
	//	  }
	//	}
	//
	// JSON `{"type": "A", ...}` will be parsed into field `a` (MessageA).
	//
	// optional string json_discriminator_value = 525000216;
	E_JsonDiscriminatorValue = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[5]
	// Delegates subtype resolution to a field's message type.
	// The field's message type must itself be a supertype. The parser flattens
	// both the parent and subtype fields into a single JSON object.
	//
	// See (internal link) for details and examples.
	//
	// optional bool subtype_source_field = 525000217;
	E_SubtypeSourceField = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[6]
	// Similar to `json_discriminator`, but the key does NOT correspond to a real
	// proto field in the target message. It is used for routing during parsing
	// and injected during serialization.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message MessageA {
	//	  string value = 1;
	//	  reserved type; // 'type' is not in proto
	//	}
	//
	// JSON `{"type": "A", "value": "foo"}` -> Proto `value: "foo"`.
	// The `"type": "A"` is used to select `MessageA` but not stored.
	//
	// optional string json_only_discriminator = 525000218;
	E_JsonOnlyDiscriminator = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[7]
	// Used on a `genai.Struct` field. Any properties in the JSON object that do
	// not match known proto fields are collected into this struct. During
	// serialization, these properties are flattened back into the parent object.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message MyMessage {
	//	  string name = 1;
	//	  .genai.Struct extra = 2 [(gaos.parsing.additional_properties) =
	//	  true];
	//	}
	//
	// JSON `{"name": "test", "foo": "bar"}` -> Proto `name: "test"`,
	// `extra: {fields { key: "foo" value { string_value: "bar" } } }`.
	//
	// optional bool additional_properties = 525000219;
	E_AdditionalProperties = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[8]
	// Allows specifying multiple discriminator values that map to this field.
	// This is used in implicit/explicit union mode when multiple JSON
	// discriminator values should resolve to the same proto field.
	//
	// See (internal link) for details and examples.
	//
	// repeated string json_discriminator_values = 525000220;
	E_JsonDiscriminatorValues = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[9]
	// Allows a field to also be parsed from a shorthand JSON form.
	//
	// The annotation value is a dot-separated path starting with the annotated
	// field's own name. When present, the parser accepts either the full nested
	// JSON object or just the descendant's value directly.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message Inner {
	//	  repeated string texts = 1;
	//	  int32 num = 2;
	//	}
	//	message Outer {
	//	  Inner inner = 1 [
	//	    (gaos.parsing.add_union_value) = "inner.texts",
	//	    (gaos.parsing.add_union_value) = "inner.texts[0]",
	//	    (gaos.parsing.add_union_value) = "inner.num"
	//	  ];
	//	}
	//
	//	// All of these parse into an Outer message:
	//	{ "inner": { "texts": ["a"], "num": 1 } }  // full form
	//	{ "inner": ["a", "b"] }                // shorthand (via "inner.texts")
	//	{ "inner": "a" }                       // shorthand(via "inner.texts[0]")
	//	{ "inner": 42 }                        //   shorthand (via "inner.num")
	//
	// Serialization always produces the full form.
	//
	// For repeated fields, a path ending on the repeated field accepts an
	// array; appending "[0]" accepts a single value and auto-wraps it into a
	// one-element list.
	//
	// Multiple annotations are allowed on the same field, but each must
	// resolve to a distinct JSON type.
	//
	// repeated string add_union_value = 525000221;
	E_AddUnionValue = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[10]
	// Used on map fields. Allows the map to be parsed from either a standard JSON
	// object or a JSON array of key-value objects.
	//
	// See (internal link) for details and examples.
	//
	// optional bool flexible_map = 525000222;
	E_FlexibleMap = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[11]
	// Specifies the target schema name to be generated for sub-content union
	// definitions in OpenAPI generation. Example:
	// [(gaos.parsing.sub_content_name) = "ThoughtSummaryContent"]
	//
	// optional string sub_content_name = 525000227;
	E_SubContentName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[12]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Overrides the string representation of an enum value in JSON.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	enum MyEnum {
	//	  ENUM_VALUE_FOO = 1 [(gaos.parsing.enum_value_name) = "foo"];
	//	}
	//
	// Proto `ENUM_VALUE_FOO` -> JSON `"foo"`.
	//
	// optional string enum_value_name = 535802949;
	E_EnumValueName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[13]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Injects a fixed key-value pair into the JSON representation of the message.
	// Useful for adding type tags required by external APIs.
	//
	// See (internal link) for details and examples.
	//
	// Example:
	//
	//	message MyMessage {
	//	  option (gaos.parsing.add_static_field) = { key: "object", value:
	//	  "interaction" }; string name = 1;
	//	}
	//
	// Proto `name: "test"` -> JSON `{"object": "interaction", "name": "test"}`.
	//
	// optional gaos.parsing.StaticJsonField add_static_field = 535801962;
	E_AddStaticField = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[14]
	// Specifies the JSON representation of this message type.
	// When set, all fields of this type are automatically treated
	// according to the specified JSON type by the parser, serializer,
	// and OAD generator.
	//
	// optional gaos.parsing.JsonType message_json_type = 535801963;
	E_MessageJsonType = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[15]
)

var File_google_antigravity_proto_genai_json_annotations_proto protoreflect.FileDescriptor

const file_google_antigravity_proto_genai_json_annotations_proto_rawDesc = "" +
	"\n" +
	"5google/antigravity/proto/genai_json_annotations.proto\x12\fgaos.parsing\x1a google/protobuf/descriptor.proto\"9\n" +
	"\x0fStaticJsonField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*e\n" +
	"\bJsonType\x12\x19\n" +
	"\x15JSON_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JSON_TYPE_OBJECT\x10\x01\x12\x13\n" +
	"\x0fJSON_TYPE_ARRAY\x10\x02\x12\x13\n" +
	"\x0fJSON_TYPE_VALUE\x10\x03:<\n" +
	"\bis_union\x12\x1d.google.protobuf.OneofOptions\x18ݺ\xab\xfa\x01 \x01(\bR\aisUnion:H\n" +
	"\x0esubtype_source\x12\x1d.google.protobuf.OneofOptions\x18\u07ba\xab\xfa\x01 \x01(\bR\rsubtypeSource:B\n" +
	"\vis_required\x12\x1d.google.protobuf.OneofOptions\x18ߺ\xab\xfa\x01 \x01(\bR\n" +
	"isRequired:@\n" +
	"\n" +
	"union_name\x12\x1d.google.protobuf.OneofOptions\x18ຫ\xfa\x01 \x01(\tR\tunionName:P\n" +
	"\x12json_discriminator\x12\x1d.google.protobuf.FieldOptions\x18\x97\xbc\xab\xfa\x01 \x01(\tR\x11jsonDiscriminator:[\n" +
	"\x18json_discriminator_value\x12\x1d.google.protobuf.FieldOptions\x18\x98\xbc\xab\xfa\x01 \x01(\tR\x16jsonDiscriminatorValue:S\n" +
	"\x14subtype_source_field\x12\x1d.google.protobuf.FieldOptions\x18\x99\xbc\xab\xfa\x01 \x01(\bR\x12subtypeSourceField:Y\n" +
	"\x17json_only_discriminator\x12\x1d.google.protobuf.FieldOptions\x18\x9a\xbc\xab\xfa\x01 \x01(\tR\x15jsonOnlyDiscriminator:V\n" +
	"\x15additional_properties\x12\x1d.google.protobuf.FieldOptions\x18\x9b\xbc\xab\xfa\x01 \x01(\bR\x14additionalProperties:]\n" +
	"\x19json_discriminator_values\x12\x1d.google.protobuf.FieldOptions\x18\x9c\xbc\xab\xfa\x01 \x03(\tR\x17jsonDiscriminatorValues:I\n" +
	"\x0fadd_union_value\x12\x1d.google.protobuf.FieldOptions\x18\x9d\xbc\xab\xfa\x01 \x03(\tR\raddUnionValue:D\n" +
	"\fflexible_map\x12\x1d.google.protobuf.FieldOptions\x18\x9e\xbc\xab\xfa\x01 \x01(\bR\vflexibleMap:K\n" +
	"\x10sub_content_name\x12\x1d.google.protobuf.FieldOptions\x18\xa3\xbc\xab\xfa\x01 \x01(\tR\x0esubContentName:M\n" +
	"\x0fenum_value_name\x12!.google.protobuf.EnumValueOptions\x18\xc5\xe8\xbe\xff\x01 \x01(\tR\renumValueName:l\n" +
	"\x10add_static_field\x12\x1f.google.protobuf.MessageOptions\x18\xea\xe0\xbe\xff\x01 \x01(\v2\x1d.gaos.parsing.StaticJsonFieldR\x0eaddStaticField:g\n" +
	"\x11message_json_type\x12\x1f.google.protobuf.MessageOptions\x18\xeb\xe0\xbe\xff\x01 \x01(\x0e2\x16.gaos.parsing.JsonTypeR\x0fmessageJsonTypeB\xd1\x01\n" +
	"\x10com.gaos.parsingB\x19GenaiJsonAnnotationsProtoP\x01ZQgithub.com/go-steer/antigravity-sdk-go/internal/genproto/google/antigravity/proto\xa2\x02\x03GPX\xaa\x02\fGaos.Parsing\xca\x02\fGaos\\Parsing\xe2\x02\x18Gaos\\Parsing\\GPBMetadata\xea\x02\rGaos::Parsingb\beditionsp\xe9\a"

var file_google_antigravity_proto_genai_json_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_antigravity_proto_genai_json_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_antigravity_proto_genai_json_annotations_proto_goTypes = []any{
	(JsonType)(0),                         // 0: gaos.parsing.JsonType
	(*StaticJsonField)(nil),               // 1: gaos.parsing.StaticJsonField
	(*descriptorpb.OneofOptions)(nil),     // 2: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),     // 3: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.MessageOptions)(nil),   // 5: google.protobuf.MessageOptions
}
var file_google_antigravity_proto_genai_json_annotations_proto_depIdxs = []int32{
	2,  // 0: gaos.parsing.is_union:extendee -> google.protobuf.OneofOptions
	2,  // 1: gaos.parsing.subtype_source:extendee -> google.protobuf.OneofOptions
	2,  // 2: gaos.parsing.is_required:extendee -> google.protobuf.OneofOptions
	2,  // 3: gaos.parsing.union_name:extendee -> google.protobuf.OneofOptions
	3,  // 4: gaos.parsing.json_discriminator:extendee -> google.protobuf.FieldOptions
	3,  // 5: gaos.parsing.json_discriminator_value:extendee -> google.protobuf.FieldOptions
	3,  // 6: gaos.parsing.subtype_source_field:extendee -> google.protobuf.FieldOptions
	3,  // 7: gaos.parsing.json_only_discriminator:extendee -> google.protobuf.FieldOptions
	3,  // 8: gaos.parsing.additional_properties:extendee -> google.protobuf.FieldOptions
	3,  // 9: gaos.parsing.json_discriminator_values:extendee -> google.protobuf.FieldOptions
	3,  // 10: gaos.parsing.add_union_value:extendee -> google.protobuf.FieldOptions
	3,  // 11: gaos.parsing.flexible_map:extendee -> google.protobuf.FieldOptions
	3,  // 12: gaos.parsing.sub_content_name:extendee -> google.protobuf.FieldOptions
	4,  // 13: gaos.parsing.enum_value_name:extendee -> google.protobuf.EnumValueOptions
	5,  // 14: gaos.parsing.add_static_field:extendee -> google.protobuf.MessageOptions
	5,  // 15: gaos.parsing.message_json_type:extendee -> google.protobuf.MessageOptions
	1,  // 16: gaos.parsing.add_static_field:type_name -> gaos.parsing.StaticJsonField
	0,  // 17: gaos.parsing.message_json_type:type_name -> gaos.parsing.JsonType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	16, // [16:18] is the sub-list for extension type_name
	0,  // [0:16] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_google_antigravity_proto_genai_json_annotations_proto_init() }
func file_google_antigravity_proto_genai_json_annotations_proto_init() {
	if File_google_antigravity_proto_genai_json_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_antigravity_proto_genai_json_annotations_proto_rawDesc), len(file_google_antigravity_proto_genai_json_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 16,
			NumServices:   0,
		},
		GoTypes:           file_google_antigravity_proto_genai_json_annotations_proto_goTypes,
		DependencyIndexes: file_google_antigravity_proto_genai_json_annotations_proto_depIdxs,
		EnumInfos:         file_google_antigravity_proto_genai_json_annotations_proto_enumTypes,
		MessageInfos:      file_google_antigravity_proto_genai_json_annotations_proto_msgTypes,
		ExtensionInfos:    file_google_antigravity_proto_genai_json_annotations_proto_extTypes,
	}.Build()
	File_google_antigravity_proto_genai_json_annotations_proto = out.File
	file_google_antigravity_proto_genai_json_annotations_proto_goTypes = nil
	file_google_antigravity_proto_genai_json_annotations_proto_depIdxs = nil
}
