// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command structured_output asks the agent for a typed JSON payload instead of
// prose.
//
// A response schema is worth reaching for when the answer feeds a database, an
// API, or another program: it removes the parsing step, and it steers the
// model's reasoning as well as its output, because the schema is enforced
// natively rather than requested politely in the prompt.
//
// Here the agent pulls raw meeting notes from a tool and distills them into a
// MeetingSummary.
//
//	go run ./examples/getting_started/structured_output
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	antigravity "github.com/go-steer/antigravity-sdk-go"
)

// ActionItem is one commitment made in a meeting.
type ActionItem struct {
	Assignee string `json:"assignee" jsonschema:"description=The person assigned to the action item."`
	Task     string `json:"task" jsonschema:"description=A description of the task to be completed."`
	Deadline string `json:"deadline" jsonschema:"description=The date or time by which the task should be completed."`
}

// MeetingSummary is the shape the agent must answer in. WithResponseSchema
// derives the JSON Schema from it by reflection, so the Go type is the single
// source of truth.
type MeetingSummary struct {
	ActionItems []ActionItem `json:"action_items" jsonschema:"description=Every action item generated by the meeting."`
}

type notesArgs struct {
	MeetingID string `json:"meeting_id" jsonschema:"description=The ID of the meeting to fetch notes for."`
}

func fetchMeetingNotes(_ context.Context, args notesArgs) (string, error) {
	if args.MeetingID != "meeting-2026-05" {
		return "Error: Meeting notes not found.", nil
	}
	return "Discussed launch timeline for project X. Alice agreed to update " +
		"the textproto tests by Monday. Bob mentioned he will run the final " +
		"E2E benchmarks tomorrow. I will push the release build once the " +
		"tests are green.", nil
}

func main() {
	if err := run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context) error {
	agent, err := antigravity.New(ctx,
		antigravity.WithTools(antigravity.MustNewTool(
			"fetch_unstructured_meeting_notes",
			"Retrieves the raw unstructured notes for a given meeting ID.",
			fetchMeetingNotes)),
		antigravity.WithResponseSchema[MeetingSummary](),
	)
	if err != nil {
		return err
	}
	defer agent.Close()

	const prompt = "Use the fetch_unstructured_meeting_notes tool to retrieve " +
		"notes for 'meeting-2026-05' and return the meeting summary with the " +
		"appropriate action item list. Ensure each action item includes " +
		"'assignee', 'task', and 'deadline'."

	fmt.Println("  Sending prompt to agent...")
	resp, err := agent.Chat(ctx, antigravity.Text(prompt))
	if err != nil {
		return err
	}

	// StructuredOutput waits for the turn to end, then returns the raw JSON the
	// model produced under the schema. A nil result means it produced none.
	raw, err := resp.StructuredOutput()
	if err != nil {
		return err
	}
	if raw == nil {
		text, err := resp.Wait()
		if err != nil {
			return err
		}
		fmt.Println("  No structured summary was produced.")
		fmt.Println("  Final text response:", text)
		return nil
	}

	var summary MeetingSummary
	if err := json.Unmarshal(raw, &summary); err != nil {
		return fmt.Errorf("decoding meeting summary: %w", err)
	}

	fmt.Println("\n  === Structured meeting action items ===")
	for _, item := range summary.ActionItems {
		fmt.Printf("  - Assignee: %s\n", item.Assignee)
		fmt.Printf("    Task:     %s\n", item.Task)
		fmt.Printf("    Deadline: %s\n\n", item.Deadline)
	}

	return nil
}
